apiVersion: v1 #version of API - current supporting
kind: Namespace # kind of resources
metadata: # describe information or data of resources
  name: nginx
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: nginx
  name: nginx-replicas
  labels:
    app: nginx-replicas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-replicas
  template:
    metadata:
      labels:
        app: nginx-replicas
        app_kind: backend_api
    spec:
      # nodeSelector:
      #   "kubernetes.io/hostname": aks-nodepool-13859459-vmss000000
      containers:
        - image: busybox:latest
          name: my-alpin
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: 256m
            requests:
              memory: 512Mi
              cpu: 256m
          env:
            - name: HELLO
              value: "HOW ARE YOU"
